# Python en pocos pasos

Este no es un overview completo de Python o de programación.

Este notebook contine los siguientes tópicos en el orden que se indica:

* Tipos de datos
    * Números
    * Cadenas
    * Impresión
    * Listas
    * Diccionarios
    * Booleanos
    * Tuplas
    * Conjuntos
* Operadores de comparación
* Sentencias if,elif, else
* Bucles for
* Bucles while
* range()
* listas por comprensión
* funciones
* expresiones lambda
* map y filter
* métodos
* arreglos con numpy
____

Propiedad de la FISI, pedir permiso a Kevin Tupac Agüero.

# **Estructura de Control Secuencial**


## Teoria

In [1]:
# Suma
1 + 1

2

In [ ]:
# Multiplicacion
1 * 3

3

In [ ]:
# divicion
1 / 2

0.5

In [ ]:
# division entera
5 // 2

2

In [ ]:
# Potenciacion
2 ** 4

16

In [ ]:
# Modulo
4 % 2

0

In [ ]:
# Modulo
5 % 2

1

In [ ]:
# Operaciones con parentesis
(2 + 3) * (5 + 5)

50

### Asignación de variables

In [ ]:
# No puede comenzar con números o caracteres especiales
nombre_de_variable = 2

In [ ]:
x = 2
y = 3

In [ ]:
z = x + y

### Cadenas

In [ ]:
'comillas simples'

'comillas simples'

In [ ]:
"comillas dobles"

'comillas dobles'

In [ ]:
"envolver otras 'citas'"

"envolver otras 'citas'"

In [ ]:
'envolver otras "citas"'

'envolver otras "citas"'

### Impresión

In [ ]:
x = 'hola'

In [ ]:
x

'hola'

In [ ]:
print(x)

hola


In [ ]:
numero = 12
nombre = 'Samuel'

In [ ]:
print('Mi número es: {uno}, y mi nombre es: {dos}'.format(uno=numero,dos=nombre))

Mi número es: 12, y mi nombre es: Samuel


In [ ]:
print('Mi número es: {}, y mi nombre es: {}'.format(numero,nombre))

Mi número es: 12, y mi nombre es: Samuel


### Listas

In [ ]:
[1,2,3]

[1, 2, 3]

In [ ]:
['hi',1,[1,2]]

['hi', 1, [1, 2]]

In [ ]:
mi_lista = ['a','b','c']

In [ ]:
mi_lista.append('d')

In [ ]:
mi_lista

['a', 'b', 'c', 'd']

In [ ]:
mi_lista[0]

'a'

In [ ]:
mi_lista[1]

'b'

In [ ]:
mi_lista[1:]

['b', 'c', 'd']

In [ ]:
mi_lista[:1]

['a']

In [ ]:
mi_lista[0] = 'NUEVO'

In [ ]:
mi_lista

['NUEVO', 'b', 'c', 'd']

In [ ]:
mi_lista.pop(1)
mi_lista

['NUEVO', 'c', 'd']

In [ ]:
mi_lista.remove('c')
mi_lista

['NUEVO', 'd']

In [ ]:
anidado = [1,2,3,[4,5,['objetivo']]]

In [ ]:
anidado[3]

[4, 5, ['objetivo']]

In [ ]:
anidado[3][2]

['objetivo']

In [ ]:
anidado[3][2][0]

'objetivo'

### Diccionarios

In [ ]:
d = {'clave1':'valor1','clave2':'valor2'}

In [ ]:
d

{'clave1': 'valor1', 'clave2': 'valor2'}

In [ ]:
d['clave1']

'valor1'

In [ ]:
d['clave1'] = 'valor3'

In [ ]:
d

{'clave1': 'valor3', 'clave2': 'valor2'}

In [ ]:
d['clave3']='valor1'

In [ ]:
d

{'clave1': 'valor3', 'clave2': 'valor2', 'clave3': 'valor1'}

In [ ]:
del d['clave1']

In [ ]:
d

{'clave2': 'valor2', 'clave3': 'valor1'}

### Booleanos

In [ ]:
True

True

In [ ]:
False

False

### Tuplas

In [2]:
t = (1,2,3,'a')

In [3]:
t

(1, 2, 3, 'a')

In [4]:
t[0]

1

In [ ]:
t[0] = 'NUEVO' # Error, porque no se puede modificar una tupla

## Problemas

### **Problema 1: Conversión de tiempo**
**Definición**: Convertir los minutos que corre un corredor en un año a meses, semanas, días, horas y minutos.  
**Entrada**: Número de minutos que corre en un año.  
**Cálculo**:  
   - Calcular el tiempo equivalente en meses, semanas, días, horas y minutos.
   
**Salida**: Mostrar los resultados en formato legible.

### **Problema 2: Cálculo de áreas**
**Definición**: Calcular el área de un círculo, el área del cuadrado inscrito y el área sombreada.  
**Entrada**: Radio del círculo.  
**Cálculo**:  \
   - Área del círculo: A = π*r^2
   - Área del cuadrado inscrito: A = 2r^2
   - Área sombreada: Resta entre las áreas del círculo y el cuadrado inscrito.
   
**Salida**: Mostrar las áreas calculadas.

### **Problema 3: Sueldo y comisiones**
**Definición**: Calcular el sueldo total de un vendedor con comisiones.  
**Entrada**: Sueldo base y tres montos de ventas.  
**Cálculo**:  
   - Comisión: \( 10\% \) del total de ventas.  
   - Sueldo total: Sumar sueldo base y comisiones.
    
**Salida**: Mostrar las comisiones y el sueldo total.  

### **Problema 4: Vueltas en una pista**
**Definición**: Determinar el tiempo que tarda un atleta en dar dos vueltas a una pista.  
**Entrada**: Velocidad del atleta (m/s) y radio de la pista (m).
**Cálculo**:  
   - Longitud de la pista: L = 2πr.  
   - El atleta descansa 1 minuto cada 1000 m.

**Salida**: Mostrar el tiempo total en minutos y segundos.  

### **Problema 5: Distribución de donaciones**
Una institución benéfica europea ha recibido tres donaciones en soles, dólares y marcos. La donación será repartida en tres rubros: 51% para la implementación de un centro de salud, 37% para un comedor de niños y el resto para gastos administrativos. Diseñe un algoritmo que determine el monto en euros que le corresponde a cada rubro. Considere que: 1 dólar = 3.52 soles, 1 dólar = 2.08 marcos, 1 dólar = 1.07 euros.  


### Problema 6: Promedio de Notas
Un alumno desea saber cuál será su calificación final en el curso de Logica de Programación. Dicha calificación se compone de los siguientes porcentajes:  
   - 55% del promedio de sus tres calificaciones parciales.  
   - 30% de la calificación del examen final.  
   - 15% de la calificación de un trabajo final.

Imprimir resultado.

### **Problema 7: Cálculo del sueldo neto**
Un empleado percibe un sueldo mensual, calcular el sueldo neto, si se realizan los siguientes descuentos:  
   - Fonavi 1%.  
   - Seguro Social 2.5%.  
   - Impuesto a la remuneración 1%.

Por otro lado, tiene una bonificación del 15% del sueldo libre de descuentos. Determine y muestre el sueldo bruto, los descuentos detallados, el sueldo neto y la bonificación.  


# **Estructura de Control Condicional o Selectiva**


## Teoria

### Conjuntos

In [ ]:
{1,2,3}

{1, 2, 3}

In [ ]:
conj = {1,2,3,1,2,1,2,3,3,3,3,2,2,2,1,1,2}
conj

{1, 2, 3}

In [ ]:
conj.add('d')
conj

{1, 2, 3, 'd'}

In [ ]:
conj.remove(2)
conj

{1, 3, 'd'}

### Operadores de comparación

In [ ]:
1 > 2

False

In [ ]:
1 < 2

True

In [ ]:
1 >= 1

True

In [ ]:
1 <= 4

True

In [ ]:
1 == 1

True

In [ ]:
'hola' != 'adios'

True

### Operadores Lógicos

In [ ]:
(1 > 2) and (2 < 3)

False

In [ ]:
(1 > 2) or (2 < 3)

True

In [ ]:
(1 == 2) or (2 == 3) or (4 == 4)

True

### Sentencias if,elif, else

In [ ]:
if 1 < 2:
    print('!Hola¡')
    print('UNMSM')

!Hola¡
UNMSM


In [ ]:
if 1 < 2:
    print('primero')
else:
    print('último')

primero


In [ ]:
if 1 > 2:
    print('primero')
else:
    print('último')

último


In [ ]:
if 1 == 2:
    print('primero')
elif 3 == 3:
    print('medio')
else:
    print('último')

medio


## Problemas

### **Problema 1: Par**
Deducir si un número es par o impar.  


### **Problema 2: Par, Impar, Nulo**
Dado un número entero; determinar si el mismo es par, impar o nulo.  


### **Problema 3: Limites**
Realizar la cuenta de los enteros comprendidos entre dos límites, mínimo y máximo.


### **Problema 4: Divisibilidad**
Para una secuencia de n números, indicar aquellos que son divisibles por 3.  


### **Problema 5: Algoritmo de edad**
Realizar un algoritmo que calcule la edad de una persona. Preguntar datos personales de la persona, como si conduce, si esta en la universidad y aproximar el resultado.


### **Problema 6: Mayor Valor**
Dado 5 números cualquiera, encontrar el mayor valor positivo si es que lo hubiera, de lo contrario dar un mensaje adecuado.  


### **Problema 7: Numero Capicua**
Dado un número natural de 3 cifras, determine si es o no es un número capicúa. Se considera que un número es capicúa cuando se lee igual de derecha a izquierda que de izquierda a derecha. Verifique que el número dado tenga sólo 3 cifras, de lo contrario dé un mensaje adecuado.  


### **Problema 8: Numeros Romanos**
Dado un número natural de no más de 3 cifras, determine su escritura en el formato romano.  


### **Problema 9: Descuentos de sueldo**
A un trabajador le descuentan de su sueldo el 10% si su sueldo es menor o igual a 1000, por encima de 1000 hasta 2000 el 5% del adicional, y por encima de 2000 el 3% del adicional. Calcular el descuento y sueldo neto que recibe el trabajador dado un sueldo.


### **Problema 10: Algoritmo de Ordenamiento**
Diseñe un algoritmo que lea tres números y los imprima de mayor a menor y de menor a mayor.  


### **Problema 11: Algoritmo de promociones**
Una tienda ha puesto en oferta la venta al por mayor de cierto producto, ofreciendo un descuento del 15% por la compra de más de 3 docenas y 10% en caso contrario. Además, por la compra de más de 3 docenas se obsequia una unidad del producto por cada docena en exceso sobre 3. Diseñe un algoritmo que determine el monto de la compra, el monto del descuento, el monto a pagar y el número de unidades de obsequio por la compra de cierta cantidad de docenas del producto.  


### **Problema 12: Triangulos**
Dados tres datos enteros positivos, que representan las longitudes de un posible triángulo, determine si los datos corresponden a un triángulo. En caso afirmativo, escriba si el triángulo es equilátero, isósceles o escaleno. Calcule además su área.  


### **Problema 13: Alquiler de autos**
Una compañía de alquiler de autos emite la factura de sus clientes teniendo en cuenta la distancia recorrida. Si la distancia no rebasa los 300 km, se cobra una tarifa fija de S/.250. Si la distancia recorrida es mayor a 300 km y hasta 1000 km, se cobra la tarifa fija más el exceso de kilómetros a razón de S/.30 por km. Si la distancia recorrida es mayor a 1000 km, la compañía cobra la tarifa fija más los km recorridos entre 300 y 1000 a razón de S/.30 y S/.20 para las distancias mayores de 1000 km. Calcular el monto que pagará un cliente.  



### **Problema 14: Cifrado**
Una empresa registra el sexo, edad y estado civil de sus empleados a través de un número entero positivo de cuatro cifras de acuerdo a lo siguiente:  
   - Primera cifra: Estado civil (1: soltero, 2: casado, 3: viudo, 4: divorciado).  
   - Siguientes dos cifras: Edad.  
   - Última cifra: Sexo (1: femenino, 2: masculino).  
   Diseñe un programa que determine el estado civil, edad y sexo de un empleado conociendo el número que empaqueta dicha información.  


### **Problema 15: Comisiones**
Calcular la comisión sobre las ventas totales de un empleado, considerando:  
   - Ventas ≤ 150: Sin comisión.  
   - Ventas > 150 y ≤ 400: Comisión del 10%.  
   - Ventas > 400: Comisión de S/.50 + 9%.  

### **Problema 16: Multiplos**
Determinar si un número es múltiplo de 2, 3, 5 o de ninguno. Considere que pueden ser múltiplos de más de uno.


### **Problema 17: Cuota de colegio**
Determinar el importe a pagar por un alumno de un instituto cuya cuota tiene
un porcentaje de descuento que se establece en la siguiente tabla y esta en
función al colegio de procedencia del alumno; asimismo los importes están
exonerados de impuestos.

| Colegio      | Instituto A | Instituto B | Instituto C |
|--------------|-------------|-------------|-------------|
| Nacional     | 50          | 40          | 30          |
| Particular   | 25          | 29          | 15          |



# **Estructura de Control Iterativa o Repetitiva**


## Teoria

### Bucles for

In [ ]:
seq = [1,2,3,4,5]

In [ ]:
for item in seq:
    print(item)

1
2
3
4
5


In [ ]:
for item in seq:
    print('Hola')

Hola
Hola
Hola
Hola
Hola


In [ ]:
for x in seq:
    print(x+x)

2
4
6
8
10


### Bucles while

In [ ]:
i = 1
while i < 5:
    print('i es: {}'.format(i))
    i = i+1

i es: 1
i es: 2
i es: 3
i es: 4


### range()

In [ ]:
range(5)

range(0, 5)

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
list(range(3,5))

[3, 4]

In [ ]:
list(range(3,25,4))

[3, 7, 11, 15, 19, 23]

### Listas por comprensión

In [ ]:
x = [1,2,3,4]

In [ ]:
salida = []
for item in x:
    salida.append(item**2)
print(salida)

[1, 4, 9, 16]


In [ ]:
salida2 = [item**2 for item in x]
print(salida2)

[1, 4, 9, 16]


## Problemas

### **Problema 1: Factorial**
Calcular el factorial de un número.  


### **Problema 2: Suma**
Calcular la suma de los números del 1 al 1000.


### **Problema 3: Multiplicacion**
Escribir un algoritmo que calcule el producto de los primeros *N* números naturales.


### **Problema 4: Problemas de series**
Resolver las siguientes series:  
   - ( S = 1 + 2 - 3 + 4 - 5 + 6 - 7 + ... + N\) (donde *N* es par).  
   - ( S = 1 + X + X^2/2! + X^3/3! + ... + X^n/N! ).  
   - ( S = 1, 1, 2, 3, 5, 8, 13, ... \) (primeros n términos de Fibonacci).

### **Problema 5: Interes**
Si un ama de casa pone su dinero en el banco a plazo fijo durante 18 años.
Para lo cual ingresa un determinado monto de dinero; ella sabe que por cada
año gana 1.22% del monto total de dinero que tiene depositado en ese
momento. Ella desearía saber después de 18 años cuánto de dinero tendrá
acumulado.


### **Problema 6:**
Generalizando el problema anterior desearíamos tener un programa en el
banco que permitiera ofrecer el servicio de calcular el monto ganado en X
años de monto depositado D para todos los clientes.  


### **Problema 7: Comisiones de sus Ventas**
Una compañía de seguros tiene contratados a N vendedores. Cada uno
hace tres ventas a la semana. Su política de pago es que un vendedor recibe
un sueldo base, y un 10% extra por comisiones de sus ventas. El gerente
de su compañía desea saber cuánto dinero obtendrá en la semana cada
vendedor por concepto de comisiones por las tres ventas realizadas, y
cuanto tomando en cuenta su sueldo base y sus comisiones.

### **Problema 8: Salarios**
En una empresa se requiere calcular el salario semanal de cada uno de los  
N obreros que laboran en ella. El salario se obtiene de la siguiente. Forma:
si el obrero trabaja 40 horas o menos se le paga $20 por hora si trabaja más
de 40 horas se le paga \$20 por cada una de las primeras 40 horas y \$25 por
cada hora extra.

### **Problema 9: Autos**
El Dpto. de Seguridad Pública y Tránsito del Distrito. desea saber, de los N
autos que entran a la ciudad de Lima, cuantos entran con calcomanía de
cada color. Conociendo el último dígito de la placa de cada automóvil se
puede determinar el color de la calcomanía utilizando la siguiente relación:

|    Digito   |    Color    |
|-------------|-------------|
|   1 - 2     | Amarilla    |
|   3 - 4     | Rosa        |
|   5 - 6     | Roja        |
|   7 - 8     | Verde       |
|   9 - 0     | Azul        |


# Extras

## funciones

In [ ]:
def mi_func(param1='Hola'):
    """
    Docstring goes here.
    """
    print(param1)

In [ ]:
mi_func

<function __main__.mi_func(param1='Hola')>

In [ ]:
mi_func()

Hola


In [ ]:
mi_func('Adios')

Adios


In [ ]:
mi_func(param1='Hasta Luego')

Hasta Luego


In [ ]:
def cuadrado(x):
    return x**2

In [ ]:
salida = cuadrado(3)

In [ ]:
print(salida)

9


In [ ]:
def ent_mod(a,b):
    e = a//b
    r = a%b
    return e,r

In [ ]:
m,n = ent_mod(15,2)
print("la división entera es",m)
print("el módulo es",n)

la división entera es 7
el módulo es 1


## expresiones lambda

In [ ]:
def por2(var):
    return var*2

In [ ]:
por2(2)

4

In [ ]:
lambda var: var*2

<function __main__.<lambda>(var)>

## map y filter

In [ ]:
seq = [1,2,3,4,5]

In [ ]:
map(por2,seq)

In [ ]:
list(map(por2,seq))

[2, 4, 6, 8, 10]

In [ ]:
list(map(lambda var: var*2,seq))

[2, 4, 6, 8, 10]

In [ ]:
filter(lambda item: item%2 != 0,seq)

In [ ]:
list(filter(lambda item: item%2 != 0,seq))

[1, 3, 5]

## métodos

In [ ]:
st = 'Hola mi nombre es Sam'

In [ ]:
st.lower()

'hola mi nombre es sam'

In [ ]:
st.upper()

'HOLA MI NOMBRE ES SAM'

In [ ]:
st.split()

['Hola', 'mi', 'nombre', 'es', 'Sam']

In [ ]:
tweet = '¡Arriba Perú! #Deportes'

In [ ]:
tweet.split('#')

['¡Arriba Perú! ', 'Deportes']

In [ ]:
tweet.split('#')[1]

'Deportes'

In [ ]:
d

{'clave2': 'valor2', 'clave3': 'valor1'}

In [ ]:
d.keys()

dict_keys(['clave2', 'clave3'])

In [ ]:
d.items()

dict_items([('clave2', 'valor2'), ('clave3', 'valor1')])

In [ ]:
lst = [1,2,3]

In [ ]:
lst.pop()

3

In [ ]:
lst

[1, 2]

In [ ]:
'x' in [1,2,3]

False

In [ ]:
'x' in ['x','y','z']

True

## Arreglos

In [ ]:
import numpy as np

De 1 dimensión

In [ ]:
a = np.array([0,1,2,3,4,5])

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.ndim

1

In [ ]:
a.shape

(6,)

In [ ]:
len(a)

6

De 2 y 3 dimensiones

In [ ]:
b = np.array([[3,2,4],[8,5,4]])
b

array([[3, 2, 4],
       [8, 5, 4]])

In [ ]:
b.shape

(2, 3)

In [ ]:
len(b)

2

In [ ]:
c = np.array([[[3,2,5],[5,6,7]],[[9,8,5],[6,2,1]]])

In [ ]:
c

array([[[3, 2, 5],
        [5, 6, 7]],

       [[9, 8, 5],
        [6, 2, 1]]])

In [ ]:
c.shape

(2, 2, 3)

In [ ]:
ceros = np.zeros((3,5))

In [ ]:
ceros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
unos = np.ones((3,5))

In [ ]:
unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
dia = np.eye(5)
dia

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
d = np.arange(8)
d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
e = np.arange(5,15,5)
e

array([ 5, 10])

In [ ]:
f = np.linspace(0,100,21)
f

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

# Gracias por resolver todos los problemas.
Autor: Kevin Tupac Agüero